- name: 'Umount requested lv'
  mount:
    path: '{{ item }}'
    state: absent
  with_items: "{{ mountpoint_list|map(attribute='mount')|list }}"

- name: 'Sets lv as unactive'
  lvol:
    vg: '{{ vg_name }}'
    lv: '{{ item.lv_name }}'
    active: False
  with_items: '{{ lv_list }}'

- name: 'remove lv'
  lvol:
    vg: '{{ vg_name }}'
    lv: '{{ item.lv_name }}'
    state: absent
    force: True
  with_items: '{{ lv_list }}'

- debug:
    var: ansible_lvm
  when: debug|bool

- name: 'remove pv'
  lvg:
    vg: '{{ vg_name }}'
    pvs: '{{ _drive_to_remove }}'
    state: absent
  when: vg_name != ""
  register: remove_pv

- debug:
    var: remove_pv
  when: debug|bool
